[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "recorder-cli"
version = "0.3.0"
description = "A modern high-performance CLI tool for continuous screen & audio recording on Wayland"
authors = [{name = "sevelebeci"}]
dependencies = [
    "rich>=13.0.0",
]
requires-python = ">=3.8"

[project.scripts]
recorder = "recorder.cli:main"
